### ISSUE TITLE
'progress' is declared but its value is never read

### ISSUE THREAD

**Issue by jere-co** [studio-freight/satus#11]
On line 34 in `/components/parallax/index.js` a `progress` const is declared, but never read again. 

I would have done a pull request, but I'm not immediately sure what this was made for, so thought to create an issue instead.

**Comment by arzafran** [comment]
Hey! thanks for pointing this out, yes, that variable was not used, i've safely removed it in [this commit](https://github.com/studio-freight/satus/commit/ef992fa961cd2c97d33de805db5dd4738d73884e).
